
// this file is generated — do not edit it


declare module '$env/private' {
    export const SERVER: string;
    export const NVM_INC: string;
    export const TERM_PROGRAM: string;
    export const NODE: string;
    export const ANDROID_HOME: string;
    export const NVM_CD_FLAGS: string;
    export const npm_package_devDependencies_typescript: string;
    export const INIT_CWD: string;
    export const SHELL: string;
    export const TERM: string;
    export const npm_package_devDependencies_vite: string;
    export const TMPDIR: string;
    export const TERM_PROGRAM_VERSION: string;
    export const NODE_AUTH_TOKEN: string;
    export const npm_package_scripts_dev: string;
    export const MallocNanoZone: string;
    export const ORIGINAL_XDG_CURRENT_DESKTOP: string;
    export const ZDOTDIR: string;
    export const npm_package_dependencies_core: string;
    export const npm_package_devDependencies_vite_plugin_browser_sync: string;
    export const npm_config_registry: string;
    export const USER: string;
    export const NVM_DIR: string;
    export const npm_package_description: string;
    export const npm_package_license: string;
    export const npm_package_dependencies_mdsvex: string;
    export const COMMAND_MODE: string;
    export const PNPM_SCRIPT_SRC_DIR: string;
    export const npm_package_devDependencies_vite_tsconfig_paths: string;
    export const SSH_AUTH_SOCK: string;
    export const __CF_USER_TEXT_ENCODING: string;
    export const npm_package_devDependencies_postcss: string;
    export const npm_execpath: string;
    export const PATH: string;
    export const __CFBundleIdentifier: string;
    export const USER_ZDOTDIR: string;
    export const npm_package_author: string;
    export const PWD: string;
    export const npm_package_devDependencies_tailwindcss: string;
    export const npm_command: string;
    export const npm_lifecycle_event: string;
    export const LANG: string;
    export const npm_package_name: string;
    export const npm_package_devDependencies__sveltejs_vite_plugin_svelte: string;
    export const npm_package_devDependencies__tsconfig_svelte: string;
    export const NODE_PATH: string;
    export const npm_package_scripts_build: string;
    export const XPC_FLAGS: string;
    export const VSCODE_GIT_ASKPASS_EXTRA_ARGS: string;
    export const npm_config_node_gyp: string;
    export const XPC_SERVICE_NAME: string;
    export const npm_package_version: string;
    export const VSCODE_INJECTION: string;
    export const npm_package_devDependencies_autoprefixer: string;
    export const HOME: string;
    export const SHLVL: string;
    export const npm_package_type: string;
    export const VSCODE_GIT_ASKPASS_MAIN: string;
    export const npm_package_dependencies_hono: string;
    export const LOGNAME: string;
    export const npm_package_dependencies_svelte: string;
    export const npm_lifecycle_script: string;
    export const VSCODE_GIT_IPC_HANDLE: string;
    export const GITHUB_TOKEN: string;
    export const NVM_BIN: string;
    export const npm_package_devDependencies_vite_plugin_simple_scope: string;
    export const npm_config_user_agent: string;
    export const GIT_ASKPASS: string;
    export const VSCODE_GIT_ASKPASS_NODE: string;
    export const npm_package_dependencies__hono_node_server: string;
    export const npm_package_dependencies_svelte_preprocess: string;
    export const npm_config_init_author_name: string;
    export const COLORTERM: string;
    export const npm_node_execpath: string;
    export const NODE_ENV: string;
}
declare module '$env/public' {
    export const PUBLIC_SERVER: string;
}
